# Generated by Django 6.0.3 on 2026-03-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporada',
            name='campeon',
        ),
        migrations.AddField(
            model_name='temporada',
            name='foto_1',
            field=models.ImageField(blank=True, null=True, upload_to='hall_of_fame/'),
        ),
        migrations.AddField(
            model_name='temporada',
            name='puesto_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporada',
            name='puesto_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='temporada',
            name='puesto_3',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
